package com.example.chatbot.main.presentation.game_screen.model

import com.example.chatbot.main.data.database_messages.model.Message
import com.example.chatbot.main.domain.instruction_factory.GPTResponse

sealed class QuizEvent {

    // Represents a new message sent by the user.
    class NewUserMessage(val content: String) : QuizEvent()

    // Represents a new message generated by the GPT model.
    class NewChatGptMessage<T : GPTResponse>(val response: T) : QuizEvent()

    // Represents the selection of a new answer in the quiz.
    class NewAnswerPicked(val index: Int) : QuizEvent()

    // Represents the completion of the quiz with a final grade.
    class GameCompleted(val finalGrade: Double) : QuizEvent()

    class ConversationInit(val message: Message) : QuizEvent()
}
