package com.example.chatbot.main.data.message_database.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents metadata for a conversation session in the local storage database.
 *
 * The instances of this class are stored in a table named "session_table" using Room Persistence Library.
 *
 * @property uid Unique identifier for the session metadata. Auto-generated by the database.
 * @property userUid Unique identifier for the user associated with the session.
 * @property timestamp The timestamp when the session metadata was created or updated.
 * @property topicsUids A string representing the unique identifiers of the topics related to the session.
 *
 * @PrimaryKey Marks the 'uid' property as the primary key for the database and indicates it is auto-generated.
 *
 * @Entity(tableName = "session_table")
 * Indicates that instances of this class will be stored in a table named "session_table" in the local database.
 */
@Entity(tableName = "session_table")
class SessionMetadata(
    @PrimaryKey val uid: Long,
    val userUid: String,
    val timestamp: Long,
    val topicsUids: String
)

